let lessons = [
    {
      id: 1001,
      subject: "Math",
      location: "Nairobi",
      price: 100,
      space: 5,
      image: "images/Math.png",
      rating: 1,
    },
    {
      id: 1002,
      subject: "English",
      location: "Mombasa",
      price: 150,
      space: 5,
      image: "images/English.png",
      rating: 3,
    },
    {
      id: 1003,
      subject: "Chemistry",
      location: "Nakuru",
      price: 200,
      space: 5,
      image: "images/Chemistry.png",
      rating: 5,
    },
    {
      id: 1004,
      subject: "Biology",
      location: "Diani",
      price: 250,
      space: 5,
      image: "images/Biology.png",
      rating: 4,
    },
    {
      id: 1005,
      subject: "Physics",
      location: "Narok",
      price: 300,
      space: 5,
      image: "images/Physics.png",
      rating: 7,
    },
    {
      id: 1006,
      subject: "Business",
      location: "Thika",
      price: 350,
      space: 5,
      image: "images/Business.png",
      rating: 6,
    },
    {
      id: 1007,
      subject: "Economics",
      location: "Kilifi",
      price: 400,
      space: 5,
      image: "images/Economics.png",
      rating: 3,
    },
    {
      id: 1008,
      subject: "Geography",
      location: "Watamu",
      price: 450,
      space: 5,
      image: "images/Geography.png",
      rating: 4,
    },
    {
      id: 1009,
      subject: "History",
      location: "Lamu",
      price: 500,
      space: 5,
      image: "images/History.png",
      rating: 7,
    },
    {
      id: 1010,
      subject: "ITs",
      location: "Naivasha",
      price: 550,
      space: 5,
      image: "images/IT.png",
      rating: 2,
    },
    {
      id: 1011,
      subject: "Art",
      location: "Eldoret",
      price: 600,
      space: 10,
      image: "images/Art.png",
      rating: 5
    },
    {
      id: 1012,
      subject: "Music",
      location: "Kajiado",
      price: 650,
      space: 10,
      image: "images/Music.png",
      rating: 7
    },
  ];
  